CREATE TABLE IF NOT EXISTS marketplace_task (
    id VARCHAR(36) NOT NULL COMMENT 'Task ID',
    task_type VARCHAR(80) NOT NULL COMMENT 'Business task type',
    code VARCHAR(20) NOT NULL COMMENT 'Task code',
    country_id VARCHAR(36) NULL COMMENT 'Country ID',
    asin VARCHAR(50) NULL COMMENT 'ASIN',
    product_name VARCHAR(255) NULL COMMENT 'Product name',
    product_link VARCHAR(500) NULL COMMENT 'Marketplace product or case link',
    task_image VARCHAR(255) NOT NULL DEFAULT '/test.jpg' COMMENT 'Task image',
    shop VARCHAR(255) NULL COMMENT 'Store name',
    keyword VARCHAR(255) NULL COMMENT 'Keyword',
    quantity INT NOT NULL DEFAULT 1 COMMENT 'Task quantity',
    priority VARCHAR(20) NOT NULL DEFAULT 'NORMAL' COMMENT 'LOW, NORMAL, HIGH, URGENT',
    issue_type VARCHAR(100) NULL COMMENT 'Issue type',
    target_action VARCHAR(100) NULL COMMENT 'Target action',
    claim_reason TEXT NULL COMMENT 'Claim or operation reason',
    evidence_link VARCHAR(500) NULL COMMENT 'Evidence link',
    evidence_image VARCHAR(255) NULL COMMENT 'Evidence image',
    channel VARCHAR(255) NULL COMMENT 'Execution channel',
    status VARCHAR(50) NOT NULL DEFAULT '0' COMMENT '0 pending, 1 processing, 2 completed, 3 canceled',
    feedback_link VARCHAR(500) NULL COMMENT 'Feedback link',
    feedback_image VARCHAR(255) NULL COMMENT 'Feedback image',
    remark TEXT NULL COMMENT 'Remark',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_marketplace_task_code (code),
    KEY idx_marketplace_task_type_status (task_type, status),
    KEY idx_marketplace_task_country_id (country_id),
    KEY idx_marketplace_task_create_time (create_time),
    CONSTRAINT fk_marketplace_task_country FOREIGN KEY (country_id) REFERENCES country (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Marketplace operation tasks';

SET @country_us = (SELECT id FROM country WHERE sort_order = 1 AND deleted = 0 ORDER BY update_time DESC LIMIT 1);
SET @country_uk = (SELECT id FROM country WHERE sort_order = 2 AND deleted = 0 ORDER BY update_time DESC LIMIT 1);
SET @country_de = (SELECT id FROM country WHERE sort_order = 3 AND deleted = 0 ORDER BY update_time DESC LIMIT 1);
SET @country_fr = (SELECT id FROM country WHERE sort_order = 4 AND deleted = 0 ORDER BY update_time DESC LIMIT 1);
SET @country_it = (SELECT id FROM country WHERE sort_order = 5 AND deleted = 0 ORDER BY update_time DESC LIMIT 1);
SET @country_es = (SELECT id FROM country WHERE sort_order = 6 AND deleted = 0 ORDER BY update_time DESC LIMIT 1);
SET @country_ca = (SELECT id FROM country WHERE sort_order = 7 AND deleted = 0 ORDER BY update_time DESC LIMIT 1);
SET @country_jp = (SELECT id FROM country WHERE sort_order = 8 AND deleted = 0 ORDER BY update_time DESC LIMIT 1);

INSERT INTO marketplace_task (
    id, task_type, code, country_id, asin, product_name, product_link, task_image,
    shop, keyword, quantity, priority, issue_type, target_action, claim_reason,
    evidence_link, evidence_image, channel, status, feedback_link, feedback_image, remark
) VALUES
    (
        '30000000-0000-0000-0000-000000000001',
        'vp_negative',
        'VPN1000',
        @country_us,
        'B0CP7M9K2Q',
        'Magnetic privacy screen protector for iPhone 15 Pro',
        'https://www.amazon.com/dp/B0CP7M9K2Q',
        '/test.jpg',
        'NorthPeak Direct',
        'privacy screen protector',
        2,
        'HIGH',
        'Verified Purchase negative review',
        'Request review removal',
        'The review contains delivery complaint and seller service wording unrelated to product quality. Prepare compliant report with order and review URL.',
        'https://sellercentral.amazon.com/reviews-vp-negative-case-1000',
        '/test.jpg',
        'Seller Central - Review Abuse',
        '1',
        NULL,
        NULL,
        'Priority because rating dropped below 4.3.'
    ),
    (
        '30000000-0000-0000-0000-000000000002',
        'counter_adult',
        'CA1000',
        @country_us,
        'B0B8T7H2L1',
        'Silicone kitchen storage mat',
        'https://www.amazon.com/dp/B0B8T7H2L1',
        '/test.jpg',
        'KitchenPro Outlet',
        'silicone kitchen mat',
        1,
        'URGENT',
        'Adult content misclassification',
        'Appeal restricted listing',
        'Listing was incorrectly classified as adult product. Images and title show ordinary kitchen accessory.',
        'https://sellercentral.amazon.com/performance/appeal/CA1000',
        '/test.jpg',
        'Account Health',
        '0',
        NULL,
        NULL,
        'Need screenshot of browse node and product detail page.'
    ),
    (
        '30000000-0000-0000-0000-000000000003',
        'counter_split_variant',
        'CSV1000',
        @country_uk,
        'B09L5W3R8M',
        'Reusable water bottle 24oz blue',
        'https://www.amazon.co.uk/dp/B09L5W3R8M',
        '/test.jpg',
        'HydroLine UK',
        'water bottle 24oz',
        3,
        'NORMAL',
        'Variant split',
        'Merge variants',
        'Child ASINs were split after catalog refresh. Submit parent-child relationship evidence and matching variation theme.',
        'https://sellercentral.amazon.co.uk/catalog/variation/CSV1000',
        '/test.jpg',
        'Catalog Support',
        '1',
        NULL,
        NULL,
        'Check whether color theme is still valid.'
    ),
    (
        '30000000-0000-0000-0000-000000000004',
        'counter_copyright_image',
        'CCI1000',
        @country_de,
        'B0C4R2Z8NM',
        'LED desk lamp with clamp',
        'https://www.amazon.de/dp/B0C4R2Z8NM',
        '/test.jpg',
        'BrightDesk EU',
        'clamp desk lamp',
        1,
        'HIGH',
        'Image copyright complaint',
        'Counter notice',
        'Complaint image belongs to the brand owner. Prepare ownership chain, original design files, and authorization letter.',
        'https://brandregistry.amazon.de/cases/CCI1000',
        '/test.jpg',
        'Brand Registry',
        '0',
        NULL,
        NULL,
        'Need brand authorization PDF later; use placeholder image now.'
    ),
    (
        '30000000-0000-0000-0000-000000000005',
        'counter_authenticity_complaint',
        'CAC1000',
        @country_fr,
        'B08N5KWB9H',
        'Wireless charger 15W',
        'https://www.amazon.fr/dp/B08N5KWB9H',
        '/test.jpg',
        'ChargeMate FR',
        'wireless charger',
        1,
        'URGENT',
        'Authenticity complaint',
        'Submit invoice proof',
        'Buyer complaint triggered authenticity review. Need invoice, supplier contact, and product packaging photos.',
        'https://sellercentral.amazon.fr/performance/notifications/CAC1000',
        '/test.jpg',
        'Account Health',
        '1',
        NULL,
        NULL,
        'Deadline within 48 hours.'
    ),
    (
        '30000000-0000-0000-0000-000000000006',
        'counter_authenticity_vp_negative',
        'CAV1000',
        @country_it,
        'B0BVY6CLRT',
        'Travel packing cubes set',
        'https://www.amazon.it/dp/B0BVY6CLRT',
        '/test.jpg',
        'TravelNova IT',
        'packing cubes',
        2,
        'HIGH',
        'Authenticity VP negative review',
        'Report review and prepare proof',
        'VP review claims counterfeit without factual support. Prepare authenticity documents and abuse report.',
        'https://sellercentral.amazon.it/reviews/CAV1000',
        '/test.jpg',
        'Review Abuse + Account Health',
        '0',
        NULL,
        NULL,
        'Coordinate review report and account health proof together.'
    ),
    (
        '30000000-0000-0000-0000-000000000007',
        'counter_product_safety',
        'CPS1000',
        @country_es,
        'B0CB8YQ2K7',
        'Kids night light projector',
        'https://www.amazon.es/dp/B0CB8YQ2K7',
        '/test.jpg',
        'DreamLight ES',
        'kids night light',
        1,
        'URGENT',
        'Product safety complaint',
        'Submit compliance documents',
        'Safety complaint requires CE report, manual, label image, and packaging photo.',
        'https://sellercentral.amazon.es/account-health/CPS1000',
        '/test.jpg',
        'Product Compliance',
        '1',
        NULL,
        NULL,
        'Use test image until document upload service is available.'
    ),
    (
        '30000000-0000-0000-0000-000000000008',
        'counter_dog',
        'CD1000',
        @country_ca,
        'B09G3HRMVB',
        'Pet grooming brush',
        'https://www.amazon.ca/dp/B09G3HRMVB',
        '/test.jpg',
        'PetCare North',
        'pet grooming brush',
        1,
        'NORMAL',
        'Listing transformed to unrelated product',
        'Restore catalog contribution',
        'Listing detail page was changed to unrelated dog product content. Collect before/after screenshots and contribution evidence.',
        'https://sellercentral.amazon.ca/catalog/CD1000',
        '/test.jpg',
        'Catalog Support',
        '0',
        NULL,
        NULL,
        'This module tracks catalog hijack or product page transformation cases.'
    ),
    (
        '30000000-0000-0000-0000-000000000009',
        'buyer_show',
        'BS1000',
        @country_jp,
        'B0C6F7J8VD',
        'Minimalist desk organizer',
        'https://www.amazon.co.jp/dp/B0C6F7J8VD',
        '/test.jpg',
        'DeskZen JP',
        'desk organizer',
        5,
        'NORMAL',
        'Buyer show content',
        'Collect buyer media',
        'Need lifestyle photos and short buyer copy for product detail page social proof.',
        'https://www.amazon.co.jp/dp/B0C6F7J8VD',
        '/test.jpg',
        'Creator / Buyer Show',
        '2',
        'https://sellercentral.amazon.co.jp/content/BS1000',
        '/test.jpg',
        'Completed sample data for media display.'
    ),
    (
        '30000000-0000-0000-0000-000000000010',
        'other_business',
        'OB1000',
        @country_us,
        'B0D1X7Q4LH',
        'Cross-border marketplace custom task',
        'https://www.amazon.com/dp/B0D1X7Q4LH',
        '/test.jpg',
        'Ops Test Store',
        'custom operation',
        1,
        'LOW',
        'Custom operation',
        'Manual follow-up',
        'General marketplace operation request that does not fit existing task templates.',
        'https://sellercentral.amazon.com/help/hub/reference/OB1000',
        '/test.jpg',
        NULL,
        '0',
        NULL,
        NULL,
        'Use this module for temporary business requests.'
    )
ON DUPLICATE KEY UPDATE
    country_id = VALUES(country_id),
    asin = VALUES(asin),
    product_name = VALUES(product_name),
    product_link = VALUES(product_link),
    task_image = VALUES(task_image),
    shop = VALUES(shop),
    keyword = VALUES(keyword),
    quantity = VALUES(quantity),
    priority = VALUES(priority),
    issue_type = VALUES(issue_type),
    target_action = VALUES(target_action),
    claim_reason = VALUES(claim_reason),
    evidence_link = VALUES(evidence_link),
    evidence_image = VALUES(evidence_image),
    channel = VALUES(channel),
    status = VALUES(status),
    feedback_link = VALUES(feedback_link),
    feedback_image = VALUES(feedback_image),
    remark = VALUES(remark),
    deleted = 0,
    update_time = CURRENT_TIMESTAMP;
